"""Single source of truth for ``X-VClaw-User-Id`` and ``Mcp-Session-Id`` validation.

Phase B of ``docs/user-isolation-via-mcp-session.md`` consolidates the
allow-list/whitelist logic that used to live in ``mcp_server._sanitize_vclaw_user_id``
into one module so ``principal_registry.bind`` and the middleware can both call the
same checks. Phase C reuses these helpers for ``ProjectWorkspace`` path
validation and adds ``sanitize_project_id`` so every project_id used in a
filesystem path comes from one allow-list.

Why these rules
---------------

- ``Mcp-Session-Id`` is normally generated by FastMCP (32-char hex or UUID); we
  only reject values that would corrupt a log line or header reflection
  (CR/LF), values that are obviously empty, and values that are absurdly long.
  We keep the validator permissive enough not to block a legitimate session
  id supplied by a future transport.
- ``X-VClaw-User-Id`` becomes the principal_id for the durable registry. Its
  charset is opaque and restricted to ``[a-zA-Z0-9._-]`` — same as vclaw's
  internal ``users.id`` — so a hostname- or path-style collision is impossible
  if it ever leaks into a filesystem path. The 128-char cap matches the
  existing vclaw convention.
- ``project_id`` is the per-user namespace inside a workspace. We keep the
  same safe charset as principal_id (no path separators, no whitespace) and
  cap the length at 64 chars — long enough for descriptive names like
  ``my-wedding-2026-clip-factory`` and short enough that a malicious caller
  cannot blow out the filesystem path budget.

Both validators are pure functions that never raise: a malformed header value
must not block an otherwise-valid request — we just return ``None`` and let the
caller decide whether to bind with no principal or skip the bind. Project_id
validation, by contrast, raises ``ValueError`` from ``ProjectWorkspace`` because
the project_id is a trusted MCP input and a malformed one means the tool call
itself is wrong — letting the call through to write garbage data would be
worse than refusing it.
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Mcp-Session-Id — opaque transport id, mostly defensive validation
# ---------------------------------------------------------------------------

MAX_SESSION_ID_LEN = 256
# Reject CR/LF (header/log injection), NUL, and the separator characters that
# would corrupt a single-line JSON or log record. Whitespace-only is handled
# by the strip() check in ``sanitize_session_id``.
_BAD_SESSION_CHARS = re.compile(r"[\r\n\0\f\v]")


def sanitize_session_id(raw: str | bytes | None) -> str | None:
    """Return a cleaned Mcp-Session-Id, or ``None`` for any reject condition.

    Reject conditions (all silent — must never raise):

    - ``None`` or non-string
    - empty after ``strip()``
    - longer than ``MAX_SESSION_ID_LEN`` (256) characters
    - contains ``\\r``, ``\\n``, NUL, or other whitespace control chars
    """
    if isinstance(raw, bytes):
        try:
            s = raw.decode("ascii")
        except UnicodeDecodeError:
            return None
    elif isinstance(raw, str):
        s = raw
    else:
        return None
    # Header values are identity-bearing opaque tokens.  Silently trimming
    # changes the value that was authenticated and lets callers disagree on
    # the owner, so whitespace padding is rejected rather than normalized.
    if s != s.strip():
        return None
    if not s:
        return None
    if len(s) > MAX_SESSION_ID_LEN:
        return None
    if _BAD_SESSION_CHARS.search(s):
        return None
    return s


# ---------------------------------------------------------------------------
# X-VClaw-User-Id / principal_id — strict allow-list, matches vclaw ``users.id``
# ---------------------------------------------------------------------------

MAX_PRINCIPAL_ID_LEN = 128
_PRINCIPAL_OK = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."
)


def sanitize_principal_id(raw: str | bytes | None) -> str | None:
    """Return a cleaned principal id (``users.id`` or ``service_id``), or ``None``.

    Same contract as the original ``mcp_server._sanitize_vclaw_user_id``:

    - non-ASCII bytes → ``None``
    - empty after ``strip()`` → ``None``
    - longer than ``MAX_PRINCIPAL_ID_LEN`` (128) characters → ``None``
    - any character outside ``_PRINCIPAL_OK`` → ``None``
    """
    if raw is None:
        return None
    if isinstance(raw, bytes):
        try:
            s = raw.decode("ascii")
        except UnicodeDecodeError:
            return None
    else:
        try:
            s = str(raw)
            s.encode("ascii")  # validate round-trip parity with the bytes path
        except (UnicodeEncodeError, UnicodeDecodeError):
            return None
    if s != s.strip():
        return None
    s = s.strip()
    if not s:
        return None
    if len(s) > MAX_PRINCIPAL_ID_LEN:
        return None
    # Dot segments are syntactically allowed by the character allow-list but
    # are filesystem navigation components in the legacy namespace fallback.
    if s in {".", ".."}:
        return None
    for ch in s:
        if ch not in _PRINCIPAL_OK:
            return None
    return s


# ---------------------------------------------------------------------------
# project_id — workspace sub-directory under a principal namespace
# ---------------------------------------------------------------------------

MAX_PROJECT_ID_LEN = 64
# Reuse the same safe character set as principal_id: a project_id is a
# filesystem sub-directory component under ``projects/users/<ns>/<id>/``,
# so it must reject path separators, CR/LF, whitespace, and NUL — exactly
# what ``_PRINCIPAL_OK`` forbids. The 64-char cap is shorter than principal
# id (128) on purpose: project_ids are user-chosen, often descriptive, and
# there is no operational reason to need more than 64 characters.
_PROJECT_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def sanitize_project_id(raw: str | bytes | None) -> str | None:
    """Return a cleaned project_id for ``ProjectWorkspace``, or ``None``.

    Tighter than ``sanitize_principal_id``: the first character must be a
    letter or digit (no leading dot/dotdot/underscore that could survive as
    a filesystem oddity), and the length cap is 64 rather than 128. Same
    reject rules as the principal-id layer (non-ASCII, empty, control chars).

    Used by ``lib.project_workspace.ProjectWorkspace.for_current_principal``
    before computing any filesystem path; ``ProjectWorkspace`` raises
    ``ValueError`` when this returns ``None`` because a bad id is a
    programmer/contract error rather than a header-level soft failure.
    """
    if raw is None:
        return None
    if isinstance(raw, bytes):
        try:
            s = raw.decode("ascii")
        except UnicodeDecodeError:
            return None
    else:
        try:
            s = str(raw)
            s.encode("ascii")
        except (UnicodeEncodeError, UnicodeDecodeError):
            return None
    if s != s.strip():
        return None
    s = s.strip()
    if not s:
        return None
    if len(s) > MAX_PROJECT_ID_LEN:
        return None
    if not _PROJECT_ID_RE.fullmatch(s):
        return None
    return s
